<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Technician extends CI_Controller
{
    private $user;
    public function __construct(){parent::__construct();if(!$this->session->userdata('user'))redirect('login');$this->user=(object)$this->session->userdata('user');if($this->user->nama_role!=='Teknisi')show_error('Halaman ini khusus teknisi.',403);}
    public function index(){ $data=array('new'=>$this->Ticket_model->list(array('status'=>1)),'mine'=>$this->Ticket_model->list(array('teknisi_id'=>$this->user->id)));$this->load->view('layouts/header',array('title'=>'Meja Teknisi'));$this->load->view('technician/index',$data);$this->load->view('layouts/footer'); }
    public function accept($id){$ticket=$this->Ticket_model->find($id);if(!$ticket||$ticket->status_id!=1)show_error('Tiket tidak tersedia.');$code=ticket_code('TRM',$id);$this->db->insert('ticket_handling',array('ticket_id'=>$id,'teknisi_id'=>$this->user->id,'kode_barcode_terima'=>$code,'waktu_terima'=>date('Y-m-d H:i:s')));$this->Ticket_model->change_status($ticket,2,$this->user->id);$this->session->set_flashdata('success','Tiket diterima. Kode penerimaan: '.$code);redirect('tickets/'.$id);}
    public function update($id){$ticket=$this->Ticket_model->find($id);if(!$ticket||!$ticket->handling||$ticket->handling->teknisi_id!=$this->user->id)show_error('Anda bukan teknisi penanganan tiket ini.',403);if($this->input->method()==='post'){$old=$ticket->handling;$data=array('analisa_keluhan'=>$this->input->post('analisa_keluhan',TRUE),'penyelesaian'=>$this->input->post('penyelesaian',TRUE));$action=$this->input->post('action');if($action==='start'&&!$old->waktu_mulai){$data['waktu_mulai']=date('Y-m-d H:i:s');$this->Ticket_model->change_status($ticket,3,$this->user->id);}if($action==='finish'){$data['waktu_selesai']=date('Y-m-d H:i:s');$data['kode_selesai']=ticket_code('SLS',$id);$this->Ticket_model->change_status($ticket,4,$this->user->id);}$this->db->where('id',$old->id)->update('ticket_handling',$data);foreach($data as $key=>$value){if((string)$old->$key!==(string)$value)$this->Ticket_model->log($id,$key,$old->$key,$value,$this->user->id);}$this->session->set_flashdata('success','Pembaruan pekerjaan tersimpan.');}redirect('tickets/'.$id);}
}
