<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Ticket_model extends CI_Model
{
    public function statuses(){return $this->db->order_by('urutan')->get('status_tiket')->result();}
    public function list($filters=array()){$this->db->select('t.*, s.nama_status, s.color_code, u.nama_unit, j.nama_jenis, h.teknisi_id, tek.nama teknisi')->from('tickets t')->join('status_tiket s','s.id=t.status_id')->join('units u','u.id=t.unit_id','left')->join('jenis_keluhan j','j.id=t.jenis_keluhan_id','left')->join('ticket_handling h','h.ticket_id=t.id','left')->join('users tek','tek.id=h.teknisi_id','left');if(!empty($filters['user_id']))$this->db->where('t.user_id',$filters['user_id']);if(!empty($filters['teknisi_id']))$this->db->where('h.teknisi_id',$filters['teknisi_id']);if(!empty($filters['status']))$this->db->where('t.status_id',$filters['status']);return $this->db->order_by('t.created_at','DESC')->get()->result();}
    public function find($id){$ticket=$this->db->select('t.*, s.nama_status, s.color_code, u.nama_unit, j.nama_jenis')->from('tickets t')->join('status_tiket s','s.id=t.status_id')->join('units u','u.id=t.unit_id','left')->join('jenis_keluhan j','j.id=t.jenis_keluhan_id','left')->where('t.id',$id)->get()->row();if(!$ticket)return FALSE;$ticket->handling=$this->db->select('h.*, u.nama teknisi')->from('ticket_handling h')->join('users u','u.id=h.teknisi_id')->where('h.ticket_id',$id)->get()->row();$ticket->spareparts=$this->db->select('ts.*, s.nama_sparepart, s.satuan')->from('ticket_sparepart ts')->join('sparepart s','s.id=ts.sparepart_id','left')->where('ts.ticket_id',$id)->get()->result();$ticket->logs=$this->db->select('l.*, u.nama')->from('ticket_logs l')->join('users u','u.id=l.diubah_oleh','left')->where('l.ticket_id',$id)->order_by('l.waktu_perubahan','DESC')->get()->result();return $ticket;}
    public function create($data){$this->db->trans_start();$sequence=$this->db->where('created_at >=',date('Y-m-d 00:00:00'))->where('created_at <=',date('Y-m-d 23:59:59'))->count_all_results('tickets')+1;$data['no_tiket']=ticket_number($sequence);$data['tanggal_lapor']=date('Y-m-d H:i:s');$data['status_id']=1;$data['created_at']=date('Y-m-d H:i:s');$this->db->insert('tickets',$data);$id=$this->db->insert_id();$this->log($id,'status','','Baru',$data['created_by']);$this->db->trans_complete();return $id;}
    public function log($ticket_id,$field,$old,$new,$user_id){$this->db->insert('ticket_logs',array('ticket_id'=>$ticket_id,'field_yang_diubah'=>$field,'nilai_lama'=>$old,'nilai_baru'=>$new,'diubah_oleh'=>$user_id,'waktu_perubahan'=>date('Y-m-d H:i:s')));}
    public function change_status($ticket,$status_id,$by){$new=$this->db->get_where('status_tiket',array('id'=>$status_id))->row();$this->db->where('id',$ticket->id)->update('tickets',array('status_id'=>$status_id));$this->log($ticket->id,'status',$ticket->nama_status,$new->nama_status,$by);$this->load->library('notification_lib');$this->notification_lib->status_changed($ticket->id,$new->nama_status);}
    public function summary(){return $this->db->select('s.nama_status, s.color_code, COUNT(t.id) total')->from('status_tiket s')->join('tickets t','t.status_id=s.id','left')->group_by('s.id')->order_by('s.urutan')->get()->result();}
}
