<style>
.detail-actions{display:flex;align-items:center;gap:10px}.ticket-workspace{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:20px;align-items:start;transition:grid-template-columns .22s ease}.ticket-workspace.log-hidden{grid-template-columns:minmax(0,1fr) 0}.ticket-content{min-width:0}.activity-panel{position:sticky;top:24px;width:auto;max-height:calc(100vh - 48px);overflow:hidden;margin:0;transition:opacity .18s ease,padding .22s ease,border-width .22s ease}.log-hidden .activity-panel{opacity:0;padding-left:0;padding-right:0;border-width:0;pointer-events:none}.activity-heading{display:flex;justify-content:space-between;align-items:start;border-bottom:1px solid var(--line);padding-bottom:15px}.activity-heading p{margin:4px 0 0;color:var(--muted);font-size:12px}.icon-button{border:0;background:#eef2f7;color:#526071;border-radius:7px;width:28px;height:28px;font-size:21px;line-height:20px;cursor:pointer}.activity-list{overflow:auto;max-height:calc(100vh - 145px);padding-top:17px}.activity-list>div{position:relative;padding:0 0 20px 19px;border-left:1px solid #dce5ef;margin-left:5px}.activity-list i{position:absolute;left:-5px;top:2px;width:9px;height:9px;border-radius:50%;background:#4d82fa}.activity-list p{margin:5px 0;color:#58687a;font-size:12px}.activity-list small{color:#93a0ae}@media(max-width:1050px){.ticket-workspace{grid-template-columns:minmax(0,1fr) 290px}}@media(max-width:850px){.ticket-workspace,.ticket-workspace.log-hidden{grid-template-columns:1fr}.activity-panel{position:static;max-height:none}.log-hidden .activity-panel{display:none}.detail-actions{align-items:flex-end;flex-direction:column}}
</style>
<div class="detail-top">
    <div><a class="back" href="<?= site_url('tickets') ?>">← Kembali ke tiket</a><p class="ticket-no"><?= html_escape($ticket->no_tiket) ?></p><h2><?= html_escape($ticket->nama_jenis ?: $ticket->jenis_lainnya) ?></h2><p class="muted">Dilaporkan <?= date('d M Y, H:i', strtotime($ticket->created_at)) ?> oleh <?= html_escape($ticket->nama_pelapor) ?></p></div>
    <div class="detail-actions"><?= status_badge($ticket->nama_status, $ticket->color_code) ?><button class="button ghost log-toggle" type="button" aria-expanded="true" onclick="toggleActivity()">◷ <span> Sembunyikan log</span></button></div>
</div>
<div class="ticket-workspace" id="ticket-workspace">
    <div class="ticket-content">
        <section class="panel"><h2>Detail laporan</h2><dl><dt>Unit</dt><dd><?= html_escape($ticket->nama_unit) ?></dd><dt>Deskripsi</dt><dd><?= nl2br(html_escape($ticket->deskripsi_aduan)) ?></dd><dt>Keluhan pengguna</dt><dd><?= nl2br(html_escape($ticket->keluhan_pengguna ?: '—')) ?></dd><dt>Kelengkapan</dt><dd><?= nl2br(html_escape($ticket->kelengkapan_barang ?: '—')) ?></dd></dl><?php if ($ticket->handling): ?><hr><h2>Penanganan teknisi</h2><dl><dt>Teknisi</dt><dd><?= html_escape($ticket->handling->teknisi) ?></dd><dt>Diterima</dt><dd><?= $ticket->handling->waktu_terima ?></dd><dt>Analisa</dt><dd><?= nl2br(html_escape($ticket->handling->analisa_keluhan ?: 'Belum diisi')) ?></dd><dt>Penyelesaian</dt><dd><?= nl2br(html_escape($ticket->handling->penyelesaian ?: 'Belum diisi')) ?></dd></dl><?php endif; ?></section>
        <?php $user = $this->session->userdata('user'); if ($user['nama_role'] === 'Teknisi' && $ticket->handling && $ticket->handling->teknisi_id == $user['id'] && $ticket->status_id < 4): ?><form class="panel work-form" method="post" action="<?= site_url('technician/update/'.$ticket->id) ?>"><h2>Update pekerjaan</h2><label>Analisa keluhan<textarea name="analisa_keluhan"><?= html_escape($ticket->handling->analisa_keluhan) ?></textarea></label><label>Penyelesaian<textarea name="penyelesaian"><?= html_escape($ticket->handling->penyelesaian) ?></textarea></label><div class="form-actions"><?php if (!$ticket->handling->waktu_mulai): ?><button class="button ghost" name="action" value="start">Mulai pengerjaan</button><?php endif; ?><button class="button primary" name="action" value="finish">Selesaikan tiket</button></div></form><?php endif; ?>
    </div>
    <aside class="panel activity-panel" id="activity-panel"><div class="activity-heading"><div><h2>Jejak aktivitas</h2><p><?= count($ticket->logs) ?> perubahan tercatat</p></div><button class="icon-button" type="button" aria-label="Sembunyikan log" onclick="toggleActivity()">×</button></div><div class="activity-list"><?php if (!$ticket->logs): ?><p class="empty">Belum ada aktivitas.</p><?php endif; foreach ($ticket->logs as $l): ?><div><i></i><b><?= html_escape($l->field_yang_diubah) ?></b><p><?= html_escape($l->nilai_lama) ?> → <?= html_escape($l->nilai_baru) ?></p><small><?= html_escape($l->nama ?: 'Sistem') ?> · <?= date('d M H:i', strtotime($l->waktu_perubahan)) ?></small></div><?php endforeach; ?></div></aside>
</div>
<script>function toggleActivity(){const w=document.getElementById('ticket-workspace'),b=document.querySelector('.log-toggle'),hidden=w.classList.toggle('log-hidden');b.setAttribute('aria-expanded',String(!hidden));b.querySelector('span').textContent=hidden?' Tampilkan log':' Sembunyikan log';localStorage.setItem('ticket-log-hidden',hidden?'1':'0')}if(localStorage.getItem('ticket-log-hidden')==='1')toggleActivity();</script>
